### ISSUE TITLE
controller turning movement speed

### ISSUE THREAD

**Issue by JaninaBistron** [origami-team/origami-vr#2]
Turning on a spot (without moving back and forward) is a little tricky.

Some solution ideas:

- Turning movement with the right toggle of the controller
- If this is not possible: additional speed-slider for the turning movement
- And if this is not possible: make the speed of turning in general a little slower

**Comment by JaninaBistron** [comment]
Change initial speed to 7.

**Comment by YouQam** [comment]
Done!
